# Component deployment flags
vpn_deploy_exit_node: false
vpn_deploy_jump_node: true
vpn_deploy_management_server: true
vpn_deploy_dashboard: true
vpn_deploy_stun_server: true
vpn_deploy_protonvpn: true
vpn_deploy_relay_server: true

# Available versions https://hub.docker.com/r/netbirdio/dashboard/tags
vpn_netbird_dashboard_version: v2.23.0
vpn_netbird_dashboard_container_user: netbirddashboard
vpn_netbird_dashboard_conf_dir: /app/netbird-dashboard/conf
# Available versions https://hub.docker.com/r/netbirdio/management/tags
vpn_netbird_mgmt_version: 0.60.7
vpn_netbird_mgmt_container_user: netbirdmgmt
vpn_netbird_mgmt_conf_dir: /app/netbird-mgmt/conf
vpn_netbird_mgmt_work_dir: /app/netbird-mgmt/work
# Available versions https://hub.docker.com/r/netbirdio/signal/tags
vpn_netbird_signal_version: 0.60.7
vpn_netbird_signal_container_user: netbirdsignal
vpn_netbird_signal_work_dir: /app/netbird-signal/work
# Available versions https://hub.docker.com/r/netbirdio/netbird/tags
# Do not update the exit_node and jump-node versions at the same time
vpn_netbird_exit_node_version: 0.60.7
vpn_netbird_exit_node_conf_dir: /app/netbird-exit-node/conf
vpn_netbird_exit_node_container_user: netbirdexitnode
vpn_netbird_jump_node_version: 0.60.7
vpn_netbird_jump_node_conf_dir: /app/netbird-jump-node/conf
vpn_netbird_jump_node_container_user: netbirdjumpnode
# Available versions https://hub.docker.com/r/netbirdio/relay/tags
vpn_netbird_relay_version: 0.60.7
vpn_netbird_relay_conf_dir: /app/netbird-relay/conf
vpn_netbird_relay_container_user: netbirdrelay
# Available versions https://hub.docker.com/r/coturn/coturn/tags
vpn_netbird_coturn_version: 4.7.0
vpn_netbird_coturn_container_user: netbirdcoturn
vpn_netbird_coturn_conf_dir: /app/netbird-coturn/conf
vpn_netbird_coturn_cert_dir: /app/netbird-coturn/certs
vpn_protonvpn_container_user: protonvpn
vpn_protonvpn_version: 7.5.3
vpn_protonvpn_conf_dir: /app/protonvpn/conf
