---
p2p_deploy_bitmagnet: true
bitmagnet_version: v0.10.0
bitmagnet_conf_dir: /app/bitmagnet/conf
bitmagnet_work_dir: /app/bitmagnet/work
# Available versions https://hub.docker.com/r/linuxserver/prowlarr/tags
prowlarr_version: 2.3.0
prowlarr_conf_dir: /app/prowlarr/conf
prowlarr_work_dir: /app/prowlarr/work
# Available versions https://hub.docker.com/r/linuxserver/qbittorrent/tags
bittorrent_version: 5.1.4
bittorrent_port: 53428
bittorrent_work_dir: /app/bittorrent/work
# Available versions https://hub.docker.com/r/linuxserver/sonarr/tags
sonarr_version: 4.0.16
sonarr_conf_dir: /app/sonarr/conf
sonarr_work_dir: /app/sonarr/work
p2p_sonarr_container_data_dir: /data
# Available versions https://hub.docker.com/r/sctx/overseerr/tags
overseerr_version: b1c6e2fdbde49859a661767e9b414555aa7abc31
overseerr_conf_dir: /app/overseerr/conf
overseerr_work_dir: /app/overseerr/work
# Available versions https://hub.docker.com/r/linuxserver/radarr/tags
p2p_radarr_version: 6.0.4
p2p_radarr_conf_dir: /app/radarr/conf
p2p_radarr_work_dir: /app/radarr/work
p2p_radarr_container_data_dir: /data
p2p_radarr_database_dir: "{{ p2p_radarr_work_dir }}/database"
p2p_radarr_db_user: radarr
p2p_radarr_main_db_name: radarrmain
p2p_radarr_logs_db_name: radarrlogs
p2p_radarr_db_container_user: postgres_radarr
p2p_radarr_container_user: radarr
p2p_flaresolverr_container_user: flaresolverr
p2p_flaresolverr_image: 21hsmw/flaresolverr:nodrivertest
