# Available versions https://hub.docker.com/repository/docker/giovannibaratta/ddclient/tags
ddclient_version: v4.0.0-rc.1
ddclient_container_user: ddclient
ddclient_conf_dir: /app/ddclient/conf
ddclient_work_dir: /app/ddclient/work
vrrp_virtual_router_id: 90
network_is_router: false